name: (Resuable) Docker build then push

env:
  ARCH_LIST: linux/arm64/v8,linux/amd64
  CURRENT_TAG: ${{ github.sha }}

on:
  workflow_call:
    inputs:
      image_name:
        description: "The base name of the image (not including tags or registry)"
        default: "ERROR"
        required: true
        type: string
      registry_name:
          description: "The name of the registry"
          default: "docker.tangerie.xyz"
          required: false
          type: string
      ref:
        description: "branch"
        default: ""
        required: true
        type: string
      path:
        default: "."
        required: false
        type: string
      build_args:
        default: ""
        required: false
        type: string
      force_build:
        default: "false"
        required: false
        type: string

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
          required: true

jobs:
  check-changes:
    runs-on: [self-hosted, builder]
    outputs:
      value: ${{ steps.changes.outputs.source }}
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          submodules: true
          clean: true
          ref: ${{ inputs.ref }}
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            source:
              - '${{inputs.path}}/**'
      - name: Debug
        run: echo File Changes in ${{ inputs.path }} = ${{ steps.changes.outputs.source }}

  docker-build-push:
    runs-on: [self-hosted, builder]
    needs: check-changes
    if: needs.check-changes.outputs.value == 'true' || inputs.force_build == 'true'
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          submodules: true
          clean: true
          ref: ${{ inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{inputs.registry_name}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print data
        run: echo Building to ${{inputs.registry_name}}/${{inputs.image_name}} ${{env.CURRENT_TAG}}

      - name: Build and push image (${{inputs.registry_name}}/${{inputs.image_name}})
        run: >
          docker buildx build 
          --push
          --platform ${{env.ARCH_LIST}}
          -t ${{inputs.registry_name}}/${{inputs.image_name}}:${{env.CURRENT_TAG}}
          -t ${{inputs.registry_name}}/${{inputs.image_name}}:latest
          --build-arg OPENAI_KEY=${{secrets.OPENAI_KEY}}
          --build-arg FONT_AWESOME_KEY=${{secrets.FONT_AWESOME_KEY}}
          --build-arg NPM_TOKEN=${{secrets.NPM_TOKEN}}
          --build-arg PRIVATE_NPM_TOKEN=${{secrets.PRIVATE_NPM_TOKEN}}
          ${{inputs.build_args}}
          ${{inputs.path}}